name: docfx build
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout 'main' branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Install .NET SDK
        run: |
          choco install dotnet --version=8.0.0 --yes

      - name: Install DocFX
        run: |
          dotnet tool install --global docfx

      - name: Copy Assembly Files
        run: |
          New-Item -Path "$env:GITHUB_WORKSPACE/" -Name "source" -ItemType Directory -Force
          New-Item -Path "$env:GITHUB_WORKSPACE/source" -Name "assembly" -ItemType Directory -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/assembly/*.dll" -Destination "$env:GITHUB_WORKSPACE/source/assembly" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/assembly/*.xml" -Destination "$env:GITHUB_WORKSPACE/source/assembly" -Force

      - name: Copy Docs Files
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/docfx.json" -Destination "$env:GITHUB_WORKSPACE/source/" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/index.md" -Destination "$env:GITHUB_WORKSPACE/source/" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/toc.yml" -Destination "$env:GITHUB_WORKSPACE/source/" -Force
          New-Item -Path "$env:GITHUB_WORKSPACE/source" -Name "docs" -ItemType Directory -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/main/docs/*" -Destination "$env:GITHUB_WORKSPACE/source/docs" -Force

      - name: Build Docs
        run: "& docfx ./docfx.json --theme modern"
        working-directory: ./source

      - name: Checkout 'gh-pages' branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clear Docs Repo
        run: Get-ChildItem -Force -Exclude .git | ForEach-Object { Remove-Item -Recurse -Verbose -Force $_ }
        working-directory: ./gh-pages

      - name: Sync New Content
        run: Copy-Item -Recurse -Verbose -Force "$env:GITHUB_WORKSPACE/source/_site/*" "$env:GITHUB_WORKSPACE/gh-pages"
        working-directory: ./gh-pages

      - name: Commit to gh-pages and Push
        run: |
          $ErrorActionPreference = "Continue"
          git add -A
          git diff HEAD -q --exit-code
          if ($?) {
            Write-Host "No changes to commit!"
            exit 0
          }
          git config --global user.name "github-actions-docfx[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Updated _site from commit $env:GITHUB_SHA on $env:GITHUB_REF"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -q origin gh-pages

        working-directory: ./gh-pages